import Link from "next/link";
import {
  ArrowRightIcon,
  BooksIcon,
  BroadcastIcon,
  ChatCircleIcon,
  CompassIcon,
} from "@phosphor-icons/react/dist/ssr";

import { EnrollButton } from "@/components/enroll-button";
import { IntakeComposer } from "@/components/intake/intake-composer";
import { Badge } from "@/components/ui/badge";
import { db } from "@/lib/db";
import { getEnrolledCourses } from "@/lib/enrollments";
import { requireLearnerContext } from "@/lib/learner";

export const metadata = { title: "Home | Basics" };

export default async function HomePage() {
  const context = await requireLearnerContext();

  const [enrolledCourses, createdCourses, recentSessions, allCourses] =
    await Promise.all([
      getEnrolledCourses(context),
      db.course.findMany({
        where: { createdByLearnerId: context.learnerId, status: "active" },
        orderBy: { createdAt: "desc" },
        include: { lessons: { select: { id: true } } },
      }),
      db.session.findMany({
        where: { learnerId: context.learnerId, courseId: { not: null } },
        orderBy: { updatedAt: "desc" },
        take: 8,
        include: {
          course: { select: { id: true, title: true } },
          lesson: { select: { id: true, title: true } },
        },
      }),
      db.course.findMany({
        where: { status: "active", createdByLearnerId: null },
        orderBy: { title: "asc" },
        select: { id: true, title: true, description: true, level: true },
      }),
    ]);

  // "Your courses" = generated by you (createdByLearnerId) ∪ enrolled.
  const yourCourses = [
    ...createdCourses,
    ...enrolledCourses.filter(
      (course) =>
        !createdCourses.some((created) => created.id === course.id),
    ),
  ];

  // Voice-first: live lesson sessions surface before chats.
  const jumpBackIn = [
    ...recentSessions.filter((session) => session.lessonId),
    ...recentSessions.filter((session) => !session.lessonId),
  ].slice(0, 4);

  // Progress proxy until real progress tracking exists: lessons touched.
  const lessonProgress = await db.session.groupBy({
    by: ["courseId", "lessonId"],
    where: {
      learnerId: context.learnerId,
      lessonId: { not: null },
      courseId: { in: yourCourses.map((course) => course.id) },
    },
  });
  const touchedByCourse = new Map<string, number>();
  for (const row of lessonProgress) {
    if (row.courseId) {
      touchedByCourse.set(
        row.courseId,
        (touchedByCourse.get(row.courseId) ?? 0) + 1,
      );
    }
  }

  const yourCourseIds = new Set(yourCourses.map((course) => course.id));
  const unenrolled = allCourses
    .filter((course) => !yourCourseIds.has(course.id))
    .slice(0, 4);

  const displayName = context.displayName?.split(/\s+/)[0];
  const today = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
  });

  return (
    <main className="flex min-h-0 flex-1">
      {/* Center: greeting + composer, vertically centered. */}
      <div className="flex min-w-0 flex-1 items-center justify-center px-6 py-12">
        <div className="w-full max-w-xl -translate-y-10 space-y-6">
          <h1 className="font-heading text-2xl font-semibold tracking-tight">
            {displayName
              ? `What do you want to learn, ${displayName}?`
              : "What do you want to learn?"}
          </h1>
          <IntakeComposer />
          <p className="text-xs text-muted-foreground">
            Describe a topic — and drop in any notes or readings — to get a
            course built just for you.
          </p>
        </div>
      </div>

      {/* Right rail: at a glance. */}
      <aside className="hidden w-90 shrink-0 flex-col overflow-y-auto px-5 py-8 lg:flex">
        {/* my-auto centers vertically but still scrolls cleanly when tall. */}
        <div className="my-auto">
          <p className="text-xs font-medium tracking-wide text-muted-foreground uppercase">
            At a glance
          </p>
          <h2 className="mt-1 mb-5 font-heading text-lg font-medium tracking-tight">
            {today}
          </h2>

          <div className="space-y-4">
          <RailSection icon={<BroadcastIcon />} label="Continue">
            {jumpBackIn.length > 0 ? (
              <div className="divide-y">
                {jumpBackIn.map((session) => {
                  const isLesson = Boolean(session.lessonId);
                  const href = isLesson
                    ? `/courses/${session.courseId}/lessons/${session.lessonId}/learn`
                    : `/courses/${session.courseId}/chats/${session.id}`;
                  const title = isLesson
                    ? (session.lesson?.title ?? "Lesson")
                    : (session.topic ?? "New chat");

                  return (
                    <Link
                      key={session.id}
                      href={href}
                      className="group flex items-center gap-2.5 px-3.5 py-2.5 transition-colors hover:bg-accent/50"
                    >
                      {isLesson ? (
                        <BroadcastIcon className="size-4 shrink-0 text-primary" />
                      ) : (
                        <ChatCircleIcon className="size-4 shrink-0 text-muted-foreground" />
                      )}
                      <span className="min-w-0 flex-1">
                        <span className="block truncate text-sm font-medium">
                          {title}
                        </span>
                        <span className="block truncate text-xs text-muted-foreground">
                          {session.course?.title}
                          {isLesson ? " · Live lesson" : " · Chat"}
                        </span>
                      </span>
                      <ArrowRightIcon className="size-3.5 shrink-0 text-muted-foreground transition-transform group-hover:translate-x-0.5" />
                    </Link>
                  );
                })}
              </div>
            ) : (
              <RailEmpty>
                No sessions yet — ask for a course on the left and your
                lessons will land here.
              </RailEmpty>
            )}
          </RailSection>

          <RailSection icon={<BooksIcon />} label="Your courses">
            {yourCourses.length > 0 ? (
              <div className="divide-y">
                {yourCourses.map((course) => {
                  const total = course.lessons.length;
                  const touched = Math.min(
                    touchedByCourse.get(course.id) ?? 0,
                    total,
                  );
                  const percent =
                    total > 0 ? Math.round((touched / total) * 100) : 0;

                  return (
                    <Link
                      key={course.id}
                      href={`/courses/${course.id}`}
                      className="block space-y-1.5 px-3.5 py-2.5 transition-colors hover:bg-accent/50"
                    >
                      <span className="block truncate text-sm font-medium">
                        {course.title}
                      </span>
                      <span className="block h-1.5 overflow-hidden rounded-full bg-muted">
                        <span
                          className="block h-full rounded-full bg-primary transition-all"
                          style={{ width: `${percent}%` }}
                        />
                      </span>
                      <span className="block text-xs text-muted-foreground">
                        {touched} of {total} lessons started
                      </span>
                    </Link>
                  );
                })}
              </div>
            ) : (
              <RailEmpty>
                Courses you create or enroll in will show up here.
              </RailEmpty>
            )}
          </RailSection>

          {unenrolled.length > 0 ? (
            <RailSection icon={<CompassIcon />} label="Start something new">
              <div className="divide-y">
                {unenrolled.map((course) => (
                  <div
                    key={course.id}
                    className="flex items-center gap-2.5 px-3.5 py-2.5"
                  >
                    <span className="min-w-0 flex-1">
                      <span className="flex items-center gap-2 truncate text-sm font-medium">
                        <Link
                          href={`/courses/${course.id}`}
                          className="truncate hover:underline"
                        >
                          {course.title}
                        </Link>
                        {course.level ? (
                          <Badge variant="secondary" className="capitalize">
                            {course.level}
                          </Badge>
                        ) : null}
                      </span>
                      {course.description ? (
                        <span className="block truncate text-xs text-muted-foreground">
                          {course.description}
                        </span>
                      ) : null}
                    </span>
                    <EnrollButton courseId={course.id} enrolled={false} />
                  </div>
                ))}
              </div>
              <Link
                href="/courses"
                className="flex items-center gap-1 border-t px-3.5 py-2 text-xs font-medium text-muted-foreground transition-colors hover:text-foreground"
              >
                Browse all courses
                <ArrowRightIcon className="size-3" />
              </Link>
            </RailSection>
          ) : null}
          </div>
        </div>
      </aside>
    </main>
  );
}

function RailSection({
  icon,
  label,
  children,
}: {
  icon: React.ReactNode;
  label: string;
  children: React.ReactNode;
}) {
  return (
    <section className="overflow-hidden rounded-xl border bg-card">
      <div className="flex items-center gap-1.5 border-b px-3.5 py-2 text-xs font-medium text-muted-foreground [&_svg]:size-3.5">
        {icon}
        {label}
      </div>
      {children}
    </section>
  );
}

function RailEmpty({ children }: { children: React.ReactNode }) {
  return (
    <p className="px-3.5 py-4 text-xs text-muted-foreground">{children}</p>
  );
}
